# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_testmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='checkbox',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testmodel',
            name='number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testmodel',
            name='name',
            field=models.CharField(max_length=10, verbose_name='blah'),
        ),
    ]
