# Generated by Django 2.0.2 on 2018-02-05 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180204_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='zipcode',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
    ]
