# Generated by Django 2.0.2 on 2018-02-10 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180205_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='area',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testmodel',
            name='email',
            field=models.EmailField(default=None, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testmodel',
            name='string',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
