# Generated by Django 2.0.2 on 2018-02-21 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20180210_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='foreign_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.City'),
        ),
        migrations.AlterField(
            model_name='testmodel',
            name='name',
            field=models.CharField(max_length=10, verbose_name='City autocomplete'),
        ),
    ]
