# Generated by Django 2.0.2 on 2018-02-22 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20180222_0913'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='testmodel',
            name='m2m',
        ),
        migrations.AddField(
            model_name='testmodel',
            name='tags',
            field=models.ManyToManyField(related_name='_testmodel_tags_+', to='api.Tag'),
        ),
    ]
